// Static demo content used exclusively by the seed script. All brand and
// product names below are fictional and created for demo purposes only.

export const categoriesData = [
  {
    name: 'Electronics',
    description: 'Headphones, wearables, cameras and audio gear for everyday life.',
    image: { url: 'https://picsum.photos/seed/cat-electronics/600/400', publicId: '' },
  },
  {
    name: 'Fashion',
    description: 'Apparel, footwear and accessories for men and women.',
    image: { url: 'https://picsum.photos/seed/cat-fashion/600/400', publicId: '' },
  },
  {
    name: 'Home & Kitchen',
    description: 'Cookware, small appliances and decor to upgrade your home.',
    image: { url: 'https://picsum.photos/seed/cat-home/600/400', publicId: '' },
  },
  {
    name: 'Beauty & Personal Care',
    description: 'Skincare, haircare and grooming essentials.',
    image: { url: 'https://picsum.photos/seed/cat-beauty/600/400', publicId: '' },
  },
  {
    name: 'Sports & Outdoors',
    description: 'Fitness equipment and outdoor gear for an active lifestyle.',
    image: { url: 'https://picsum.photos/seed/cat-sports/600/400', publicId: '' },
  },
  {
    name: 'Books',
    description: 'Guides and reads to help you learn and grow.',
    image: { url: 'https://picsum.photos/seed/cat-books/600/400', publicId: '' },
  },
  {
    name: 'Toys & Games',
    description: 'Fun for kids and family game nights.',
    image: { url: 'https://picsum.photos/seed/cat-toys/600/400', publicId: '' },
  },
  {
    name: 'Grocery',
    description: 'Pantry staples and snacks delivered to your door.',
    image: { url: 'https://picsum.photos/seed/cat-grocery/600/400', publicId: '' },
  },
];

// categoryName must match a `name` above exactly - the seed script resolves
// it to a real ObjectId before insertion.
export const productsData = [
  // ---------------- Electronics ----------------
  {
    name: 'EchoWave Pro Wireless Bluetooth Headphones',
    categoryName: 'Electronics',
    brand: 'EchoWave',
    description:
      'Over-ear wireless headphones with active noise cancellation, 40-hour battery life, and studio-tuned sound. Includes a carrying case and USB-C fast charging.',
    price: 149.99,
    discountPrice: 119.99,
    stock: 45,
    featured: true,
    images: [
      { url: 'https://picsum.photos/seed/headphones-1/800/800', publicId: '' },
      { url: 'https://picsum.photos/seed/headphones-2/800/800', publicId: '' },
    ],
  },
  {
    name: 'Vantura Pulse Smart Watch',
    categoryName: 'Electronics',
    brand: 'Vantura',
    description:
      'Fitness smartwatch with heart-rate monitoring, GPS tracking, sleep analysis and a 7-day battery life. Water resistant up to 50m.',
    price: 199.99,
    discountPrice: 169.0,
    stock: 30,
    featured: true,
    images: [
      { url: 'https://picsum.photos/seed/smartwatch-1/800/800', publicId: '' },
      { url: 'https://picsum.photos/seed/smartwatch-2/800/800', publicId: '' },
    ],
  },
  {
    name: 'Vantura ActionCam 4K',
    categoryName: 'Electronics',
    brand: 'Vantura',
    description:
      'Waterproof 4K action camera with image stabilization, wide-angle lens and Wi-Fi transfer. Perfect for travel and sports.',
    price: 129.0,
    discountPrice: 0,
    stock: 22,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/actioncam-1/800/800', publicId: '' }],
  },
  {
    name: 'EchoWave Mini Portable Bluetooth Speaker',
    categoryName: 'Electronics',
    brand: 'EchoWave',
    description: 'Compact speaker with rich bass, IPX7 waterproofing, and 12-hour playtime. Pairs with two devices at once.',
    price: 59.99,
    discountPrice: 44.99,
    stock: 80,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/speaker-1/800/800', publicId: '' }],
  },

  // ---------------- Fashion ----------------
  {
    name: "UrbanForge Men's Slim Fit Denim Jacket",
    categoryName: 'Fashion',
    brand: 'UrbanForge',
    description: 'Classic slim-fit denim jacket made from durable cotton twill with a soft brushed interior.',
    price: 79.99,
    discountPrice: 59.99,
    stock: 60,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/denimjacket-1/800/800', publicId: '' }],
  },
  {
    name: "Lumeo Women's Floral Summer Dress",
    categoryName: 'Fashion',
    brand: 'Lumeo',
    description: 'Lightweight floral print dress with adjustable straps, perfect for warm-weather days.',
    price: 54.99,
    discountPrice: 0,
    stock: 50,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/dress-1/800/800', publicId: '' }],
  },
  {
    name: 'UrbanForge Classic Leather Sneakers',
    categoryName: 'Fashion',
    brand: 'UrbanForge',
    description: 'Handcrafted genuine leather sneakers with a cushioned insole and rubber outsole for all-day comfort.',
    price: 89.99,
    discountPrice: 74.99,
    stock: 40,
    featured: true,
    images: [
      { url: 'https://picsum.photos/seed/sneakers-1/800/800', publicId: '' },
      { url: 'https://picsum.photos/seed/sneakers-2/800/800', publicId: '' },
    ],
  },
  {
    name: 'Lumeo Unisex Wool Blend Beanie',
    categoryName: 'Fashion',
    brand: 'Lumeo',
    description: 'Soft wool-blend beanie that keeps you warm without sacrificing style. One size fits most.',
    price: 19.99,
    discountPrice: 14.99,
    stock: 100,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/beanie-1/800/800', publicId: '' }],
  },

  // ---------------- Home & Kitchen ----------------
  {
    name: 'Craftline 10-Piece Stainless Steel Cookware Set',
    categoryName: 'Home & Kitchen',
    brand: 'Craftline',
    description: 'Durable stainless steel cookware with tempered glass lids and heat-resistant handles. Dishwasher safe.',
    price: 189.99,
    discountPrice: 149.99,
    stock: 25,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/cookware-1/800/800', publicId: '' }],
  },
  {
    name: 'Craftline Electric Stand Mixer',
    categoryName: 'Home & Kitchen',
    brand: 'Craftline',
    description: '6-speed stand mixer with a 5-quart stainless steel bowl, dough hook, whisk and flat beater included.',
    price: 249.99,
    discountPrice: 0,
    stock: 18,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/mixer-1/800/800', publicId: '' }],
  },
  {
    name: 'Craftline Aromatherapy Essential Oil Diffuser',
    categoryName: 'Home & Kitchen',
    brand: 'Craftline',
    description: 'Ultrasonic diffuser with 7-color LED lighting and auto shut-off. Covers rooms up to 300 sq ft.',
    price: 34.99,
    discountPrice: 27.99,
    stock: 70,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/diffuser-1/800/800', publicId: '' }],
  },

  // ---------------- Beauty & Personal Care ----------------
  {
    name: 'PureGlow Vitamin C Brightening Serum',
    categoryName: 'Beauty & Personal Care',
    brand: 'PureGlow',
    description: '20% Vitamin C serum with hyaluronic acid to brighten skin tone and reduce fine lines.',
    price: 29.99,
    discountPrice: 22.99,
    stock: 90,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/serum-1/800/800', publicId: '' }],
  },
  {
    name: 'PureGlow Ionic Professional Hair Dryer',
    categoryName: 'Beauty & Personal Care',
    brand: 'PureGlow',
    description: 'Salon-grade ionic hair dryer with 3 heat settings and a concentrator nozzle for frizz-free results.',
    price: 69.99,
    discountPrice: 0,
    stock: 35,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/hairdryer-1/800/800', publicId: '' }],
  },
  {
    name: 'PureGlow Organic Skincare Gift Set',
    categoryName: 'Beauty & Personal Care',
    brand: 'PureGlow',
    description: 'A 5-piece organic skincare set including cleanser, toner, moisturizer, eye cream and face mask.',
    price: 64.99,
    discountPrice: 49.99,
    stock: 40,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/skincareset-1/800/800', publicId: '' }],
  },

  // ---------------- Sports & Outdoors ----------------
  {
    name: 'PeakGear Premium Non-Slip Yoga Mat',
    categoryName: 'Sports & Outdoors',
    brand: 'PeakGear',
    description: 'Extra-thick 6mm yoga mat with a non-slip textured surface and carrying strap included.',
    price: 39.99,
    discountPrice: 29.99,
    stock: 85,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/yogamat-1/800/800', publicId: '' }],
  },
  {
    name: 'PeakGear Adjustable Dumbbell Set',
    categoryName: 'Sports & Outdoors',
    brand: 'PeakGear',
    description: 'Space-saving adjustable dumbbells, 5-50 lbs per hand, with a quick-select dial system.',
    price: 299.0,
    discountPrice: 259.0,
    stock: 15,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/dumbbells-1/800/800', publicId: '' }],
  },
  {
    name: 'PeakGear 2-Person Camping Tent',
    categoryName: 'Sports & Outdoors',
    brand: 'PeakGear',
    description: 'Lightweight waterproof tent with quick-pitch poles, perfect for backpacking and weekend trips.',
    price: 119.99,
    discountPrice: 0,
    stock: 28,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/tent-1/800/800', publicId: '' }],
  },

  // ---------------- Books ----------------
  {
    name: 'Mindful Productivity: A Practical Guide',
    categoryName: 'Books',
    brand: 'Norhen',
    description: 'A practical, research-backed guide to building focus, healthy habits and a sustainable productivity system.',
    price: 18.99,
    discountPrice: 13.99,
    stock: 120,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/book-1/800/800', publicId: '' }],
  },
  {
    name: "The Modern Entrepreneur's Playbook",
    categoryName: 'Books',
    brand: 'Norhen',
    description: 'A step-by-step playbook for launching and scaling a business in the digital age.',
    price: 22.99,
    discountPrice: 0,
    stock: 75,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/book-2/800/800', publicId: '' }],
  },

  // ---------------- Toys & Games ----------------
  {
    name: 'PlayNest 500-Piece Building Blocks Set',
    categoryName: 'Toys & Games',
    brand: 'PlayNest',
    description: 'Colorful, compatible building blocks that spark creativity. Includes a storage bin for easy cleanup.',
    price: 44.99,
    discountPrice: 34.99,
    stock: 55,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/blocks-1/800/800', publicId: '' }],
  },
  {
    name: 'PlayNest Remote Control Race Car',
    categoryName: 'Toys & Games',
    brand: 'PlayNest',
    description: 'High-speed RC car with full-function remote, rechargeable battery, and rugged all-terrain tires.',
    price: 49.99,
    discountPrice: 0,
    stock: 38,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/rccar-1/800/800', publicId: '' }],
  },
  {
    name: 'PlayNest Wooden Puzzle Board Game',
    categoryName: 'Toys & Games',
    brand: 'PlayNest',
    description: 'A family-friendly wooden strategy game for 2-4 players, ages 6 and up.',
    price: 24.99,
    discountPrice: 19.99,
    stock: 65,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/boardgame-1/800/800', publicId: '' }],
  },

  // ---------------- Grocery ----------------
  {
    name: 'Harvestly Organic Coffee Beans 1kg',
    categoryName: 'Grocery',
    brand: 'Harvestly',
    description: 'Single-origin, medium-roast organic coffee beans, ethically sourced and freshly roasted.',
    price: 24.99,
    discountPrice: 19.99,
    stock: 5,
    featured: true,
    images: [{ url: 'https://picsum.photos/seed/coffee-1/800/800', publicId: '' }],
  },
  {
    name: 'Harvestly Mixed Nuts & Dried Fruit Pack',
    categoryName: 'Grocery',
    brand: 'Harvestly',
    description: 'A wholesome trail mix of roasted nuts, dried cranberries and raisins. No added sugar.',
    price: 16.99,
    discountPrice: 0,
    stock: 3,
    featured: false,
    images: [{ url: 'https://picsum.photos/seed/trailmix-1/800/800', publicId: '' }],
  },
];

export const couponsData = [
  {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minimumPurchase: 0,
    expirationDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    usageLimit: null,
    isActive: true,
  },
  {
    code: 'FLAT20',
    discountType: 'fixed',
    discountValue: 20,
    minimumPurchase: 100,
    expirationDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    usageLimit: 200,
    isActive: true,
  },
  {
    code: 'SAVE15',
    discountType: 'percentage',
    discountValue: 15,
    minimumPurchase: 50,
    expirationDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    usageLimit: 500,
    isActive: true,
  },
];

// A small pool of review comments/ratings shuffled across a subset of
// products so the storefront has believable social proof out of the box.
export const reviewPool = [
  { rating: 5, title: 'Exceeded expectations', comment: 'Great quality and fast shipping. Would buy again!' },
  { rating: 4, title: 'Very happy with this', comment: 'Works exactly as described. Minor packaging issue but the product itself is great.' },
  { rating: 5, title: 'Worth every penny', comment: 'This has become part of my daily routine. Highly recommend.' },
  { rating: 3, title: 'Good, not great', comment: 'Does the job but I expected slightly better build quality for the price.' },
  { rating: 5, title: 'Perfect gift', comment: 'Bought this as a gift and they loved it. Beautiful packaging too.' },
  { rating: 4, title: 'Solid choice', comment: 'Good value for money. Delivery was quicker than expected.' },
];
